#! /bin/bash

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:
# Description:
# pidfile: /var/run/nginx.pid
# config: /usr/local/nginx/conf/nginx.conf
### END INIT INFO


prefix=/usr/local/nginx
nginxd=${prefix}/sbin/nginx
nginx_config=${prefix}/conf/nginx.conf
nginx_pid=/var/run/nginx.pid

RETVAL=0
prog="nginx"


[ -x $nginxd ] || exit 0

# Start nginx daemons functions.
start() {

	if [ -e $nginx_pid ];then
   	echo "nginx already running...."
   	exit 1
	fi

  echo -n $"Starting $prog: "

  $nginxd -c ${nginx_config}
  RETVAL=$?
  echo
   [ $RETVAL = 0 ] && touch /var/lock/subsys/nginx
  return $RETVAL
}

# Stop nginx daemons functions.
stop() {

	echo -n $"Stopping $prog: "

  $nginxd -s stop

  RETVAL=$?
  echo
		[ $RETVAL = 0 ] && rm -f /var/lock/subsys/nginx
}

reload() {

  echo -n $"Reloading $prog: "

  #kill -HUP `cat ${nginx_pid}`

  $nginxd -s reload
  RETVAL=$?
    echo
}

# See how we were called.
case "$1" in
	start)
    start
  ;;
	stop)
    stop
  ;;
	reload)
    reload
  ;;
	restart)
    stop
    start
  ;;
	status)
    status $prog
    RETVAL=$?
  ;;
	*)
		echo $"Usage: $prog {start|stop|restart|reload|status|help}"
  	exit 1
esac
exit $RETVAL
